% Create a nested container map
rxMap = containers.Map( ...
    {'ascension_island', 'hong_kong'}, ...
    {[7.95, -14.35, 728], [22.32, 114.17, 50]} ...
);

tsMap = containers.Map( ...
    {'L1', 'L2', 'L5'}, ...
    {rand(100,1), rand(100,1), rand(100,1)} ...
);

outerMap = containers.Map();
outerMap('receiver_positions') = rxMap;
outerMap('time_series') = tsMap;

% Save using v7.3 format (stores as HDF5, readable by h5py in Python)
save('containerMapData.mat', 'outerMap', '-v7.3');
